### ISSUE TITLE
1.12.3 broke compatibility with ScalaTest

### ISSUE THREAD

**Issue by ummels** [rickynils/scalacheck#165]
After upgrading from 1.12.2 to 1.12.3, all my tests defined using `org.scalatest.prop.PropertyChecks` fail with an `AbstractMethodError`. For instance, running [this spec](https://github.com/ummels/scala-prioritymap/blob/master/src/test/scala/de/ummels/prioritymap/PriorityMapSpec.scala) yields

```
scala> (new de.ummels.prioritymap.PriorityMapSpec).execute()
PriorityMapSpec:
Exception encountered when invoking run on a suite. *** ABORTED ***
  java.lang.AbstractMethodError: org.scalatest.prop.Configuration$$anon$1.TestParams()Lorg/scalacheck/Test$Parameters$TestParams$;
  at org.scalacheck.Test$Parameters$class.$init$(Test.scala:98)
  at org.scalatest.prop.Configuration$$anon$1.<init>(Configuration.scala:332)
  at org.scalatest.prop.Configuration$class.getParams(Configuration.scala:332)
  at de.ummels.prioritymap.PriorityMapSpec.getParams(PriorityMapSpec.scala:10)
  at org.scalatest.prop.GeneratorDrivenPropertyChecks$class.forAll(GeneratorDrivenPropertyChecks.scala:1093)
  at de.ummels.prioritymap.PriorityMapSpec.forAll(PriorityMapSpec.scala:10)
  at de.ummels.prioritymap.PriorityMapSpec$$anonfun$1.apply$mcV$sp(PriorityMapSpec.scala:15)
  at de.ummels.prioritymap.PriorityMapSpec$$anonfun$1.apply(PriorityMapSpec.scala:15)
  at de.ummels.prioritymap.PriorityMapSpec$$anonfun$1.apply(PriorityMapSpec.scala:15)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  ...
```

**Comment by rickynils** [comment]
Ouch. This was caused by adding a not-really-private `private[scalacheck]` method to `Test.Parameters` in 1.12.3. I have removed it now again. Please try `1.12.4-SNAPSHOT`.

**Comment by cheeseng** [comment]
hi @rickynils, 

Not sure if it is related, but I just hit a problem with 1.12.3 too when trying to use scalacheck from scalatest, you can reproduce the problem by following these steps: 

> git clone https://github.com/cheeseng/scalatest.git
> cd scalatest
> git checkout scala-js-20150522

After that you can change the following line to use 1.12.3 (or 1.12.4-SNAPSHOT, same result)

https://github.com/cheeseng/scalatest/blob/scala-js-20150522/project/scalatest.scala#L455

and then do:

> sbt scalatestAllJS/test

It would fail with something like this: 

java.lang.Exception: Invalid ScalaCheck args
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:39)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:33)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/javalanglib/src/main/scala/java/lang/Throwables.scala:24)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/javalanglib/src/main/scala/java/lang/Throwables.scala:271)
	at <jscode>.(file:/home/ricky/src/scalacheck/src/main/scala/org/scalacheck/ScalaCheckFramework.scala:30)
	at <jscode>.(file:/home/ricky/src/scalacheck/src/main/scala/org/scalacheck/ScalaCheckFramework.scala:156)
	at <jscode>.(file:/home/ricky/src/scalacheck/src/main/scala/org/scalacheck/ScalaCheckFramework.scala:156)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/test-interface/src/main/scala/org/scalajs/testinterface/internal/Master.scala:41)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/test-interface/src/main/scala/org/scalajs/testinterface/internal/Master.scala:41)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:8)
	at <jscode>.(https://raw.githubusercontent.com/scala/scala/v2.11.6/src/library/scala/util/Try.scala:191)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/test-interface/src/main/scala/org/scalajs/testinterface/internal/Master.scala:41)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/test-interface/src/main/scala/org/scalajs/testinterface/internal/Master.scala:22)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/test-interface/src/main/scala/org/scalajs/testinterface/internal/BridgeBase.scala:34)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/test-interface/src/main/scala/org/scalajs/testinterface/internal/BridgeBase.scala:19)
	at <jscode>.(https://raw.githubusercontent.com/scala-js/scala-js/v0.6.3/test-interface/src/main/scala/org/scalajs/testinterface/internal/BridgeBase.scala:19)
[error] (scalatestTestJS/test:executeTests) java.lang.Exception: Invalid ScalaCheck args

Not sure if it is expected, but it works well with 1.12.2.  The test that uses ScalaCheck and having the problem is this one: 

https://github.com/cheeseng/scalatest/blob/scala-js-20150522/scalatest-test/src/test/scala/org/scalatest/ShouldBeAnySpec.scala

**Comment by rickynils** [comment]
@cheeseng I have published a new build of `1.12.4-SNAPSHOT` that logs a bit more for your exception. The problem seems to be that ScalaCheck is provided with invalid parameters. In ScalaCheck `1.12.2` the parameters were actually not parsed at all for ScalaJS (only default params were used). In `1.12.3` the parameters are parsed properly also in the JS case. When running your build with the new logging I can see that the following (invalid) parameters are given to ScalaCheck:

```
[error] (scalatestTestJS/test:testOnly) java.lang.Exception: Invalid ScalaCheck args: List(-l, org.scalatest.tags.Slow, -m, org.scalatest, -m, org.scalactic, -m, org.scalactic.anyvals, -m, org.scalactic.algebra, -m, org.scalactic.enablers, -m, org.scalatest.fixture, -m, org.scalatest.concurrent, -m, org.scalatest.testng, -m, org.scalatest.junit, -m, org.scalatest.events, -m, org.scalatest.prop, -m, org.scalatest.tools, -m, org.scalatest.matchers, -m, org.scalatest.suiteprop, -m, org.scalatest.mock, -m, org.scalatest.path, -m, org.scalatest.selenium, -m, org.scalatest.exceptions, -m, org.scalatest.time, -m, org.scalatest.words, -m, org.scalatest.enablers, -m, org.scalautils, -oDI, -h, target/html, -u, target/junit, -fW, target/result.txt)
```

So I think this is a bug in scalatest, not ScalaCheck.

**Comment by cheeseng** [comment]
@rickynils thanks for the info, it is a good hint, the same behavior is observed when running with jvm also, I am able to fix the problem (both jvm and js) by just adding TestFrameworks.ScalaTest, and both 1.12.3 and 1.12.4-SNAPSHOT now working.  Cheers.

**Comment by ummels** [comment]
@rickynils Thanks, with 1.12.4-SNAPSHOT everything is working as expected.

**Comment by alexarchambault** [comment]
Ran into this too: https://travis-ci.org/alexarchambault/argonaut-shapeless/jobs/64441556
Switching to 1.12.4-SNAPSHOT fixed it.

Any hope of a release with it?

**Comment by rickynils** [comment]
@alexarchambault Yes, I'll release 1.12.4 as soon as I get time

**Comment by alexarchambault** [comment]
Great :-)

**Comment by rickynils** [comment]
ScalaCheck 1.12.4 has now been release, fixing these compatibility issues.
