### ISSUE TITLE
NullPointerException when using Gen.const(null) in Gen.oneOf()

### ISSUE THREAD

**Issue by JoshRosen** [rickynils/scalacheck#177]
I'm trying to write a function which accepts a `Gen` and produces a new `Gen` which sometimes returns `null`.  While working on this, I ran into an unexpected NullPointerException in ScalaCheck.  Here's a reproduction:

```scala
scala> Gen.oneOf(Arbitrary.arbitrary[Array[Byte]], Gen.const(null)).sample
java.lang.NullPointerException
	at org.scalacheck.Gen$$anonfun$containerOf$2.apply(Gen.scala:415)
	at org.scalacheck.Gen$$anonfun$containerOf$2.apply(Gen.scala:414)
	at org.scalacheck.Gen$$anon$3.sieveCopy(Gen.scala:68)
	at org.scalacheck.Gen$$anonfun$oneOf$4$$anonfun$apply$11.apply(Gen.scala:356)
	at org.scalacheck.Gen$$anonfun$oneOf$4$$anonfun$apply$11.apply(Gen.scala:356)
	at scala.collection.IndexedSeqOptimized$$anonfun$exists$1.apply(IndexedSeqOptimized.scala:40)
	at scala.collection.IndexedSeqOptimized$$anonfun$exists$1.apply(IndexedSeqOptimized.scala:40)
	at scala.collection.IndexedSeqOptimized$class.segmentLength(IndexedSeqOptimized.scala:189)
	at scala.collection.mutable.ArrayBuffer.segmentLength(ArrayBuffer.scala:47)
	at scala.collection.GenSeqLike$class.prefixLength(GenSeqLike.scala:92)
	at scala.collection.AbstractSeq.prefixLength(Seq.scala:40)
	at scala.collection.IndexedSeqOptimized$class.exists(IndexedSeqOptimized.scala:40)
	at scala.collection.mutable.ArrayBuffer.exists(ArrayBuffer.scala:47)
	at org.scalacheck.Gen$$anonfun$oneOf$4.apply(Gen.scala:356)
	at org.scalacheck.Gen$$anonfun$oneOf$4.apply(Gen.scala:356)
	at org.scalacheck.Gen$R$$anon$4$$anonfun$sieve$2.apply(Gen.scala:149)
	at org.scalacheck.Gen$R$$anon$4$$anonfun$sieve$2.apply(Gen.scala:148)
	at scala.Option.filter(Option.scala:181)
	at org.scalacheck.Gen$R$class.retrieve(Gen.scala:140)
	at org.scalacheck.Gen$R$$anon$4.retrieve(Gen.scala:146)
	at org.scalacheck.Gen$class.sample(Gen.scala:80)
	at org.scalacheck.Gen$$anon$3.sample(Gen.scala:65)
	at .<init>(<console>:9)
```

Note that

```scala
scala> Gen.const(null).sample
res29: Option[Null] = Some(null)
```

**Comment by JoshRosen** [comment]
There seems to be some sort of unexpected interaction between `null` and `Array`, since cases like

```
scala> Gen.oneOf(Gen.const(null), Gen.const("string")).sample
```

do not hit this issue.

**Comment by ChrisCoffey** [comment]
This actually occurs with any `Buildable` in head position followed by a `null`, not just `Array[_]`. This can be replicated by:

```
Gen.oneOf(Gen.listOf(Gen.const(7)),Gen.const(null) 
Gen.oneOf(Arbitrary.arbitrary[Seq[Int]], Gen.const(null))
etc...
```
However, placing `Gen.const(null)` at the head works fine as a workaround. 

I'm putting together a pull to address this.

**Comment by muhuk** [comment]
I am getting NPE with the following generator:

```scala
val genLiteralType: Gen[LiteralType] = Gen.oneOf(BooleanType :: NumberType :: TextType :: Nil)

def genAtomType: Gen[AtomType] = Gen.oneOf(
    Gen.const(SymbolType),
    genLiteralType
)
```

(Both using `1.12.5` & `1.13.1`)

If I remove the `const` one, the problem disappears. If I replicate `genLiteralType`'s list and add `SymbolType` (i.e. use just a `Gen.oneOf`) the problem disappears.

Changing the order of `const` doesn't make a difference.
