### ISSUE TITLE
Is Gen.chooseNum excluding part of the valid range of doubles?

### ISSUE THREAD

**Issue by matthewdooler** [rickynils/scalacheck#274]
Hi,

I'm using `Gen.chooseNum(Double.MinValue, Double.MaxValue)` in a generator, but it's causing the generator to fail at a high rate. Checking the source for chooseNum, it seems like `chDbl` is excluding doubles below zero in this line:
`if (d < 0 || d > Double.MaxValue) r(None)`

I think this is causing the high failure rate as it will try generating positive and negative numbers but filter out the negatives. Does this sound like a bug in chooseNum or is this the intended behaviour?

Ultimately I solved the problem by using `arbitrary[Double]` instead but still seems like something `chooseNum` should be able to do.

Many thanks!

**Comment by non** [comment]
This sounds like an issue. I'll take a look, thanks!

**Comment by non** [comment]
@matthewdooler Which version of ScalaCheck are you using? This code changed recently and it seems to be working for me on *master*. Here's the test I used:

```scala
import org.scalacheck._

case class Dbl(n: Double)
implicit val arbDbl: Arbitrary[Dbl] =
  Arbitrary(Gen.chooseNum(Double.MinValue, Double.MaxValue).map(Dbl(_)))

val p = Prop.forAll { (x: Dbl) => x == x }
p.check // + OK, passed 100 tests.
```

Please let me know if you can confirm that this is still broken (or works for you) on the newest release and/or master.

**Comment by matthewdooler** [comment]
Thanks for checking. We're on 1.12.5 which is quite old, but all our property tests fail if we try upgrading to 1.13.2:

```
[info] DeferredAbortedSuite:
[info] Exception encountered when attempting to run a suite with class name: org.scalatest.DeferredAbortedSuite *** ABORTED ***
[info]   java.lang.IncompatibleClassChangeError: Implementing class
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   ...
[error] Uncaught exception when running common.example.ExampleProperties: java.lang.IncompatibleClassChangeError: Implementing class
sbt.ForkMain$ForkError: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at common.example.ExampleProperties.<init>(ExampleProperties.scala:13)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:468)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

That's another problem though (probably some sort of conflict with other dependencies, or scala version) so unless the cause is immediately obvious I'm happy for this to be closed since you're confident master works!

**Comment by non** [comment]
OK yeah, those issues probably stem from the fact that 1.13.2 isn't binary compatible with 1.12.5, meaning any code compiled against the old version will need to be recompiled/republished for your project.

Good luck! I'm fine with leaving this open until you can confirm the fix, but I'm also fine with closing it and reopening it if you later notice problems on the newer version.

**Comment by matthewdooler** [comment]
I tried recompiling from scratch but no luck, so we'll have to find some time to have a proper look. I'll close this and reopen if we discover the bug still exists in the latest version :)
