### ISSUE TITLE
should not execute the clean task in packageBin task 

### ISSUE THREAD

**Issue by xuwei-k** [rickynils/scalacheck#327]
- http://www.scala-sbt.org/0.13/docs/Custom-Settings.html#Execution+semantics+of+tasks
- https://github.com/rickynils/scalacheck/issues/318#issuecomment-286601090

because `publishLocal` and `publish` task nondeterministic fail.

![screen shot 2017-04-14 at 22 18 29](https://cloud.githubusercontent.com/assets/389787/25044213/61b089d6-2160-11e7-91af-acc039caef8c.png)

```
java.lang.RuntimeException: Missing files for publishing:
	scalacheck/js/target/scala-2.12/scalacheck_sjs0.6_2.12-1.13.5.pom
	scalacheck/js/target/scala-2.12/scalacheck_sjs0.6_2.12-1.13.5-sources.jar
	at scala.sys.package$.error(package.scala:27)
	at sbt.IvyActions$.checkFilesPresent(IvyActions.scala:393)
	at sbt.IvyActions$.publish(IvyActions.scala:377)
	at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply$mcV$sp(IvyActions.scala:124)
	at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:124)
	at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:124)
	at sbt.IvyActions$.withChecksums(IvyActions.scala:133)
	at sbt.IvyActions$.sbt$IvyActions$$withChecksums(IvyActions.scala:128)
	at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:124)
	at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:117)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.publish(IvyActions.scala:117)
	at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1384)
	at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1383)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Missing files for publishing:
	scalacheck/jvm/target/scala-2.12/scalacheck_2.12-1.13.5-sources.jar
	at scala.sys.package$.error(package.scala:27)
	at sbt.IvyActions$.checkFilesPresent(IvyActions.scala:393)
	at sbt.IvyActions$.publish(IvyActions.scala:377)
	at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply$mcV$sp(IvyActions.scala:124)
	at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:124)
	at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:124)
	at sbt.IvyActions$.withChecksums(IvyActions.scala:133)
	at sbt.IvyActions$.sbt$IvyActions$$withChecksums(IvyActions.scala:128)
	at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:124)
	at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:117)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.publish(IvyActions.scala:117)
	at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1384)
	at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1383)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (js/*:publishLocal) Missing files for publishing:
[error] 	scalacheck/js/target/scala-2.12/scalacheck_sjs0.6_2.12-1.13.5.pom
[error] 	scalacheck/js/target/scala-2.12/scalacheck_sjs0.6_2.12-1.13.5-sources.jar
[error] (jvm/*:publishLocal) Missing files for publishing:
[error] 	scalacheck/jvm/target/scala-2.12/scalacheck_2.12-1.13.5-sources.jar
[error] Total time: 19 s, completed Apr 14, 2017 9:49:19 PM
```

**Comment by non** [comment]
It seems like we should move the `clean` step to another place, maybe something specific to the release process.

@rickynils, do you use a release script? I could always throw something together which runs whatever SBT command you use right now, with a `clean` first. What do you think?

**Comment by rickynils** [comment]
@non Yes, the `clean` step is an unreliable hack. Let's go for a release script. Much appreciated if you throw something together. The steps I do is basically these:

```
$ sbt
> project jvm
> set scalaVersion := ...
> test
> publishSigned
> set scalaVersion := ...
> ...
> project js
> ...
```

And before that I have usually tagged the release and created a `x.y.z_sonatype` branch from which I do all the release work.

**Comment by non** [comment]
Sounds great! I'll start on a release script (or possibly try to configure `sbt-release`) and send a PR as soon as I can.

**Comment by rickynils** [comment]
The `packageBin` abuse has been reverted in 9b71bb3.

**Comment by SethTisue** [comment]
thanks @rickynils!
