### ISSUE TITLE
Conflicting cross version suffix

### ISSUE THREAD

**Issue by Christewart** [rickynils/scalacheck#441]
Hi, i'm trying to publish scalacheck as part of a [`testkit`](https://github.com/bitcoin-s/bitcoin-s-core/blob/ln/project/Deps.scala#L97) jar for bitcoin-s, and i keep getting this error when trying to import the testkit into another project that also scalacheck i get this error.

```
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scalacheck:scalacheck
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error]         at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error]         at sbt.Classpaths$.$anonfun$ivyBaseSettings$64(Defaults.scala:2009)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (api / update) Conflicting cross-version suffixes in: org.scalacheck:scalacheck
```

Am i missing something obvious or is something misconfigured with scalacheck? Both deps in bitcoin-s and the project i am using this `teskit` dependency have scalacheck versioned with `%%` and are using `1.14.0`

**Comment by Christewart** [comment]
I had another depdency that had a nested scalacheck dependency.
