### ISSUE TITLE
Circe is broken in community build

### ISSUE THREAD

**Issue by ashawley** [rickynils/scalacheck#485]
There isn't a lot in master, since 1.14.0 was released, but the community build uncovered a test suite error in circe that could be ScalaCheck related:

```
[info] JsonCodecMacrosSuite:
[info] io.circe.generic.JsonCodecMacrosSuite *** ABORTED ***
[info]   java.lang.StackOverflowError:
[info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.$anonfun$arbitrarySelfRecursiveWithOption$1(JsonCodecMacrosSuite.scala:154)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority.$anonfun$arbOption$1(Arbitrary.scala:339)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority.arbitrary(Arbitrary.scala:79)
[info]   at org.scalacheck.ArbitraryLowPriority.arbitrary$(Arbitrary.scala:79)
[info]   at org.scalacheck.Arbitrary$.arbitrary(Arbitrary.scala:62)
[info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.atDepth(JsonCodecMacrosSuite.scala:147)
[info]   ...
[info] SemiautoDerivedSuite:
[info] io.circe.generic.JsonCodecMacrosSuite *** ABORTED ***
[info]   java.lang.StackOverflowError:
[info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.$anonfun$arbitrarySelfRecursiveWithOption$1(JsonCodecMacrosSuite.scala:154)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority.$anonfun$arbOption$1(Arbitrary.scala:339)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[info]   at org.scalacheck.ArbitraryLowPriority.arbitrary(Arbitrary.scala:79)
[info]   at org.scalacheck.ArbitraryLowPriority.arbitrary$(Arbitrary.scala:79)
[info]   at org.scalacheck.Arbitrary$.arbitrary(Arbitrary.scala:62)
[info]   at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.atDepth(JsonCodecMacrosSuite.scala:147)
[info]   ...
[info] Codec[Seq[WithSeqOfTagged]]
[info] - should obey codec.consistency with accumulating
[info] - should obey codec.decoder serializability
[info] - should obey codec.encoder serializability
[info] - should obey codec.roundTrip
[error] java.lang.StackOverflowError
[error] 	at io.circe.generic.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$.$anonfun$arbitrarySelfRecursiveWithOption$1(JsonCodecMacrosSuite.scala:154)
[error] 	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[error] 	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[error] 	at org.scalacheck.ArbitraryLowPriority.$anonfun$arbOption$1(Arbitrary.scala:339)
[error] 	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(Arbitrary.scala:75)
[error] 	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(Arbitrary.scala:75)
[error] 	at org.scalacheck.ArbitraryLowPriority.arbitrary(Arbitrary.scala:79)
[error] 	at org.scalacheck.ArbitraryLowPriority.arbitrary$(Arbitrary.scala:79)
[error] 	at org.scalacheck.Arbitrary$.arbitrary(Arbitrary.scala:62)
...
```

**Comment by ashawley** [comment]
Seems it could be #408.

**Comment by ashawley** [comment]
Should probably add a test to the test suite to verify `Arbitrary.arbOption` can handle recursive generators.  This wasn't a scenario that had been considered, but maybe there's a way to accommodate it by changing the frequence of `Some` v. `None`.

**Comment by ashawley** [comment]
Should be fixed in https://github.com/circe/circe/pull/1204
